### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by JEFworks** [JEFworks/MERmaid#3]
# Enhancements
- [x] Provide option to disable rotation
- [x] Loading bar
- [x] ~~Generalized gene.csv to be matrix of options where reach column may be a different category to visualize~~ gene.csv no longer used
- [x] Generalize data.csv to accommodate any number of metadata columns (including each point being a cell and metadata being numeric gene expression)
- [x] Allow for numeric / non-categorical color scales
- [x] Allow user to select colors
- [ ] Enable uploading own data
- [x] Reset to center option
- [x] ~~Prevent zooming too far away~~ Sufficient with reset

# Known bugs
- [x] Resetting gene does not automatically change point size, only color
- [x] Reset view triggers with new gene selection?

**Comment by JEFworks** [comment]
- [ ] Allow change of background color (black or white)
- [ ] Allow multiple coloring modes; allow coloring points by factor (cell-type) or coloring points by continuous variable (gene expression) mode
